# ─────────────────────────────────────────────────────────────────────────────
# FreeFollowers — app.py
# Flask backend that receives graph data from the browser extension
# and serves it back to the visualisation page.
# ─────────────────────────────────────────────────────────────────────────────
 
from flask import Flask, request, jsonify, render_template, send_from_directory
from flask_cors import CORS
from datetime import datetime, timedelta
import threading
import time
import json
import os
 
app = Flask(__name__)
 
# CORS allows the browser extension to POST from any origin
CORS(app)
 
# ── LOAD DISCONNECT.ME TRACKER LIST ──────────────────────────────────────────
# Parse services.json into a flat lookup: domain → {company, type, url}
 
CATEGORY_MAP = {
    'Advertising':           'advertiser',
    'Analytics':             'analytics',
    'Social':                'social',
    'Content':               'cdn',
    'Email':                 'analytics',
    'EmailAggressive':       'analytics',
    'FingerprintingGeneral': 'fingerprint',
    'FingerprintingInvasive':'fingerprint',
    'Cryptomining':          'cryptomining',
    'Disconnect':            'tracker',
}
 
tracker_lookup = {}
 
def load_disconnect_list():
    path = os.path.join(os.path.dirname(__file__), 'static', 'services.json')
    if not os.path.exists(path):
        print('[FreeFollowers] services.json not found — run:')
        print('[FreeFollowers] curl -o static/services.json https://github.com/disconnectme/disconnect-tracking-protection/raw/refs/heads/master/services.json')
        return
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    count = 0
    for category_name, entries in data.get('categories', {}).items():
        tracker_type = CATEGORY_MAP.get(category_name, 'tracker')
        for entry in entries:
            for company_name, details in entry.items():
                for url, domains in details.items():
                    for domain in domains:
                        tracker_lookup[domain.lower()] = {
                            'company':  company_name,
                            'type':     tracker_type,
                            'url':      url,
                            'category': category_name,
                        }
                        count += 1
    print(f'[FreeFollowers] Loaded {count} tracker domains from Disconnect.me')
 
load_disconnect_list()
 
 
# ── IN-MEMORY SESSION STORE ───────────────────────────────────────────────────
# We store graph data in a simple Python dictionary.
# Key   = session_id (random string generated by the extension)
# Value = the graph object (nodes, edges, last updated time)
#
# No database needed for now — if the server restarts, sessions reset.
# That is fine for a demo. We can add Redis later for persistence.
 
sessions = {}
sessions_lock = threading.Lock()  # prevents race conditions if two requests arrive simultaneously
 
 
# ── ROUTE 1: receive graph data from the extension ────────────────────────────
# The extension will POST to this endpoint every few seconds
# with the current state of the graph.
 
@app.route('/api/graph', methods=['POST'])
def receive_graph():
    data = request.get_json()
 
    # Basic validation — make sure we got something sensible
    if not data:
        return jsonify({'error': 'No data received'}), 400
 
    session_id = data.get('session_id')
    if not session_id:
        return jsonify({'error': 'Missing session_id'}), 400
 
    nodes = data.get('nodes', [])
    edges = data.get('edges', [])
 
    # Store it — use a lock so two simultaneous requests don't corrupt the data
    with sessions_lock:
        sessions[session_id] = {
            'session_id':   session_id,
            'nodes':        nodes,
            'edges':        edges,
            'last_updated': datetime.now().isoformat(),
            'created_at':   sessions.get(session_id, {}).get('created_at', datetime.now().isoformat())
        }
 
    print(f'[FreeFollowers] Session {session_id[:8]}... updated — '
          f'{len(nodes)} nodes, {len(edges)} edges')
 
    return jsonify({'status': 'ok', 'session_id': session_id})
 
 
# ── ROUTE 2: serve graph data to the visualisation page ──────────────────────
# The graph.html page will call this every 2 seconds to get the latest data
# and update the visualisation.
 
@app.route('/api/graph/<session_id>', methods=['GET'])
def get_graph(session_id):
    with sessions_lock:
        session = sessions.get(session_id)
 
    if not session:
        # Session not found — return empty graph
        # This happens when someone opens a link before the extension has posted
        return jsonify({
            'session_id': session_id,
            'nodes': [],
            'edges': [],
            'last_updated': None,
            'found': False
        })
 
    return jsonify({**session, 'found': True})
 
 
# ── ROUTE 3: the visualisation page ──────────────────────────────────────────
# When someone opens /graph/abc123 they see the D3 visualisation
# for that session ID.
# We serve graph.html and pass the session_id into it.
 
@app.route('/install')
def install():
    return render_template('install.html')
 
 
@app.route('/graph/<session_id>')
def graph_page(session_id):
    return send_from_directory('static', 'graph.html')
 
 
# ── ROUTE 4: landing page ─────────────────────────────────────────────────────
# The home page — explains what FreeFollowers is.
# We'll build this properly later. For now just a simple placeholder.
 
@app.route('/')
def index():
    from flask import make_response
    resp = make_response(render_template('index.html'))
    resp.headers['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
    resp.headers['Pragma'] = 'no-cache'
    return resp
 
 
# ── ROUTE 5: serve the tracker lookup table ───────────────────────────────────
# graph.html fetches this once on load so it can classify every domain
@app.route('/api/trackers')
def get_trackers():
    return jsonify(tracker_lookup)
 
 
# ── ROUTE 6: stats — useful for debugging ────────────────────────────────────
# Visit /api/stats in your browser to see all active sessions.
# Remove this or protect it with a password before going public.
 
@app.route('/api/stats')
def stats():
    with sessions_lock:
        summary = [
            {
                'session_id':   sid[:8] + '...',   # only show first 8 chars for privacy
                'nodes':        len(s['nodes']),
                'edges':        len(s['edges']),
                'last_updated': s['last_updated']
            }
            for sid, s in sessions.items()
        ]
    return jsonify({
        'active_sessions': len(sessions),
        'sessions': summary
    })
 
 
# ── CLEANUP: remove old sessions ─────────────────────────────────────────────
# Run a background thread that deletes sessions older than 2 hours.
# Prevents memory growing forever if many people use the tool.
 
def cleanup_old_sessions():
    while True:
        time.sleep(300)  # check every 5 minutes
        cutoff = datetime.now() - timedelta(hours=2)
        with sessions_lock:
            to_delete = [
                sid for sid, s in sessions.items()
                if datetime.fromisoformat(s['last_updated']) < cutoff
            ]
            for sid in to_delete:
                del sessions[sid]
                print(f'[FreeFollowers] Cleaned up expired session {sid[:8]}...')
 
cleanup_thread = threading.Thread(target=cleanup_old_sessions, daemon=True)
cleanup_thread.start()
 
 
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == '__main__':
    # debug=True means Flask auto-reloads when you save the file
    # Remove debug=True when running in production on Hetzner
    # use_reloader=False because we already have a background thread running
    print('[FreeFollowers] Starting server...')
    app.run(host='0.0.0.0', port=5000, debug=True, use_reloader=False)