services:
  web:
    build: .
    restart: unless-stopped
    expose:
      - "5000"
    networks:
      caddy_network:
        aliases:
          - freefollowers

networks:
  caddy_network:
    external: true
    name: ${CADDY_NETWORK}